apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels: {{- include "mylabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: 30001
      port: 80
      {{- else if eq .Values.service.type "LoadBalancer" }}
      port: 8001
      {{- else }}
      port: 8180
      {{- end }}
      protocol: TCP
      name: http
  selector:
    app: nginx
